name: Docker PostGIS CI

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: bash

jobs:

  make-docker-images:
    strategy:
      matrix:
        # list compatible with arm64; exclude the latest version set for use with "include" below
        postgres: [14, 15]
        postgis: ['3.3']
        latest: [false]
    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }}
    runs-on: ubuntu-20.04
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU for amd64 and arm64
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: sogis/postgis
          labels: |
            org.opencontainers.image.title=postgis
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.base.name=docker.io/postgis/postgis:${{ env.VERSION }}
          tags: |
            type=raw,value=${{ env.VERSION }},enable=true,priority=200
            type=raw,value=latest,enable=${{ matrix.latest }},priority=200

      - name: Login to Docker Container Registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Multi-platform build and push
        uses: docker/build-push-action@v4.0.0
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ env.VERSION }}
          file:  ${{ env.VERSION }}/Dockerfile
          tags: |
            sogis/postgis:${{ env.VERSION }}
            ghcr.io/sogis-oereb/postgis:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=postgis
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.base.name=docker.io/postgres
          pull: true
          push: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}